# Generated by Django 2.0.3 on 2018-03-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Daftar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
